apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fiap-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fiapcontainer
  template:
    metadata:
      labels:
        app: fiapcontainer
    spec:
      containers:
        - name: fiapzookeeper
          image: "confluentinc/cp-zookeeper:latest"
          env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: 2181
          - name: ZOOKEEPER_TICK_TIME
            value: 2000
          ports:
            - name: http
              containerPort: 2181
        - name: fiapkafka
          image: "confluentinc/cp-kafka:latest"
          env:
          - name: KAFKA_BROKER_ID
            value: 1
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: 2181
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEX
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: PLAINTEX
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: 1
          ports:
            - name: http
              containerPort: 9092
